name: sandbox
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.*
  - snakemake
  - bwa
  - freebayes
  - vt
  - samtools
  - bcftools
  - bedops
  - qualimap
  - AdapterRemoval
  - seqhax
  - pigz

# test
